language: ruby
rvm: 2.3.1
install:
  - bundle install --jobs=3 --retry=3
  - npm install -g gulp-cli
  - npm install -g bower
  - npm install
  - bower install
before_script:
  - export NODE_ENV=production
script:
  - gulp publish
