# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: makabde.me

email: hello@makabde.me

description: "Product Designer (UX / UI / Research) & Front-End Developer - Switzerland & Remote"

baseurl: ""

url: "http://localhost:9999" # the base hostname & protocol for your site

twitter_username: makabde
github_username:  makabde

# Jekyll settings

source: ./src
destination: ./build

# Build settings

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
