# ========================================
# Site settings
# ========================================

title: "makabde.me"
title_separator: "×"
description: "Personal website of freelance product designer slash coder Mak Abdennabi - Switzerland & Remote"

language: "en"

logo: assets/images/makabde-logo.png

url: "http://localhost:9999"

social:
  name: "Mak Abdennabi"
  links:
    - https://dribbble.com/makabde
    - https://github.com/makabde
    - http://codepen.io/makabde/
    - https://twitter.com/makabde
    - https://ch.linkedin.com/in/makabde

twitter:
  username: makabde


# ========================================
# Site owner info
# ========================================

author:
  name: "Mak Abdennabi"
  url: "http://makabde.me/about/"
  bio: "Product designer, coder, father, one hand amputee."
  picture: /assets/images/makabde-picture.png
  twitter: "makabde"
  github: "makabde"

# ========================================
# Jekyll configuration
# ========================================

source: ./src
destination: ./build

lsi                      : false
future                   : true
show_drafts              : true
markdown                 : kramdown
kramdown:
  toc_levels             : 1..3
  input                  : GFM
  hard_wrap              : false
  auto_ids               : true
  entity_output          : as_char
  smart_quotes           : lsquo,rsquo,ldquo,rdquo
  enable_coderay         : false
highlighter              : rouge

# ========================================
# Jekyll plugins
# ========================================

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
