# ========================================
# Site settings
# ========================================

url: "http://makabde.me"

# ========================================
# Jekyll configuration
# ========================================

future: false
show_drafts: false
