# ========================================
# Site settings
# ========================================

url: "http://makabde.me"

# ========================================
# Jekyll configuration
# ========================================

future                   : true
show_drafts              : true
